# Generated by Django 4.0.4 on 2022-05-15 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_orderitem_product'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
