# Generated by Django 4.0.4 on 2022-05-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_alter_orderitem_product'),
        ('session', '0002_alter_customsession_order_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customsession',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.order'),
        ),
    ]
