# Generated by Django 4.0.4 on 2022-05-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_categorie_product_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categorie',
            field=models.ManyToManyField(blank=True, to='catalogue.categorie'),
        ),
    ]
