# Generated by Django 4.0.4 on 2022-05-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('postCode', models.IntegerField(blank=True)),
                ('adress', models.CharField(max_length=500)),
                ('adressComplement', models.CharField(max_length=500)),
            ],
        ),
    ]
