# Generated by Django 4.0.4 on 2022-05-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_adress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.adress'),
        ),
    ]
