# Generated by Django 4.0.4 on 2022-05-12 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0011_remove_order_cart_order_user_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='adress',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='adress',
            old_name='adressComplement',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='adress',
            old_name='postCode',
            new_name='zip_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adress', to='cart.adress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.order'),
        ),
    ]
