# Generated by Django 4.0.4 on 2022-05-16 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_product_price'),
        ('cart', '0016_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orderItems', related_query_name='orderItems', to='catalogue.product'),
        ),
    ]
